#!/usr/bin/env bash
set -euo pipefail

if [ $# -lt 1 ]; then
    echo "usage: ./re xNNNNNN"
    echo "example: ./re x009500"
    exit 1
fi

photo="$1"
photo="${photo#photos/}"

echo "restart photos/${photo}"
./star "${photo}"
